name: Build Cloak Shared Libraries

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NDK_VERSION: r25c
      GO_VERSION: "1.21.1"
      NDK_HOME: ${{ runner.temp }}/android-ndk

    steps:
      - name: Checkout Cloak repository
        uses: actions/checkout@v3
        with:
          repository: cbeuw/Cloak
          ref: master # You can specify a commit or tag if needed

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Download Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-${{ env.NDK_VERSION }}-linux.zip -O ${{ runner.temp }}/android-ndk.zip
          unzip -q ${{ runner.temp }}/android-ndk.zip -d ${{ runner.temp }}
          mv ${{ runner.temp }}/android-ndk-${{ env.NDK_VERSION }} ${{ env.NDK_HOME }}
          echo "ANDROID_NDK_HOME=${{ env.NDK_HOME }}" >> $GITHUB_ENV

      - name: Set up NDK environment variables
        run: |
          echo "PATH=${{ env.ANDROID_NDK_HOME }}/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=${{ env.ANDROID_NDK_HOME }}" >> $GITHUB_ENV

      - name: Build Cloak for arm64-v8a
        env:
          CC: aarch64-linux-android21-clang
          GOOS: android
          GOARCH: arm64
          CGO_ENABLED: 1
        run: |
          mkdir -p build/arm64-v8a
          go build -buildmode=c-shared -o build/arm64-v8a/libcloak.so

      - name: Build Cloak for armeabi-v7a
        env:
          CC: armv7a-linux-androideabi21-clang
          GOOS: android
          GOARCH: arm
          CGO_ENABLED: 1
        run: |
          mkdir -p build/armeabi-v7a
          go build -buildmode=c-shared -o build/armeabi-v7a/libcloak.so

      - name: Build Cloak for x86
        env:
          CC: i686-linux-android21-clang
          GOOS: android
          GOARCH: 386
          CGO_ENABLED: 1
        run: |
          mkdir -p build/x86
          go build -buildmode=c-shared -o build/x86/libcloak.so

      - name: Build Cloak for x86_64
        env:
          CC: x86_64-linux-android21-clang
          GOOS: android
          GOARCH: amd64
          CGO_ENABLED: 1
        run: |
          mkdir -p build/x86_64
          go build -buildmode=c-shared -o build/x86_64/libcloak.so

      - name: Upload Cloak shared libraries
        uses: actions/upload-artifact@v4
        with:
          name: cloak-shared-libraries
          path: build/
